name: Build Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1

    - name: Download a file
      id: download
      run: |
        SONARR_RELEASE=$(curl -sL "https://services.sonarr.tv/v1/download/main?version=3&os=linux" | jq -r '.version')
        sonarr_url="https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux"
        echo ::set-output name=SONARR_RELEASE::${SONARR_RELEASE}
        echo ::set-output name=sonarr_url::${sonarr_url}
        echo ::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |
          linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.download.outputs.IMAGE_NAME }}:latest
        build-args: |
          SONARR_RELEASE=${{ steps.download.outputs.SONARR_RELEASE }}
          sonarr_url=${{ steps.download.outputs.sonarr_url }}
