name: Build Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
  push:

env:
  IMAGE_NAME: dpvduncan/sonarr:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1

    - name: Prepare variables
      run: |
        SONARR_RELEASE=$(curl -sL "https://services.sonarr.tv/v1/download/main?version=3&os=linux" | jq -r '.version')
        sonarr_url="https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux"
        echo "SONARR_RELEASE=${SONARR_RELEASE}" >> ${GITHUB_ENV}
        echo "sonarr_url=${sonarr_url}" >> ${GITHUB_ENV}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |
          linux/amd64
        push: true
        tags: ${{ env.IMAGE_NAME }}
        build-args: |
          SONARR_RELEASE=${{ env.SONARR_RELEASE }}
          sonarr_url=${{ env.sonarr_url }}
